version: '1'
services:
  web: 
    image: glitchedvixen-website:latest
    ports: 
      - "80:80"
    volumes:
      - ./:/var/www/html/
    environment:
      XDEBUG_MODE: "develop,debug,coverage"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9000 start_with_request=yes idekey=VSCODE"
      XDEBUG_SESSION: VSCODE